### ISSUE TITLE
Create a nice logo image for Kobin

### ISSUE THREAD

**Issue by c-bata** [c-bata/kobin#13]
Hmmm...

**Comment by c-bata** [comment]
![kobin](https://cloud.githubusercontent.com/assets/5564044/13204621/bec8d728-d917-11e5-9f17-2a6865b5e8a7.png)

**Comment by c-bata** [comment]
@denari Is there a something nice one?

**Comment by c-bata** [comment]
![kobin](https://cloud.githubusercontent.com/assets/5564044/13287647/75c434ce-db4b-11e5-974d-f109a6dd0eb4.png)

**Comment by c-bata** [comment]
<img width="401" alt="2016-02-24 23 10 45" src="https://cloud.githubusercontent.com/assets/5564044/13287725/ded9c1f4-db4b-11e5-9345-7e5d99498bdc.png">

**Comment by c-bata** [comment]
<img width="746" alt="2016-02-24 23 42 29" src="https://cloud.githubusercontent.com/assets/5564044/13288656/4f79b5e6-db50-11e5-8b7d-03cfb3984ccc.png">

**Comment by denari** [comment]
# 1st : fonts

Kobin is a nice , and simple framework.
But fonts used in these logos are not simple.

Optima is the simplest in these fonts, but i think kobin's image is simpler than the font's image.
So i think you may use simpler font. ex, [san francisco](https://developer.apple.com/fonts/) , helvetica ...


# 2nd : corks

Why do you cork a (this logo's) 小瓶(kobin)?
Kobin is not closed, isn't it??
It receive a http requests and respond when developers use kobin's `Request and Response object`.
And you want a nice pull request on github, are't you??

I think kobin is open. so logo's 小瓶 may be uncorked.


# 3rd : color

what is kobin's theme color??
i think blue is nice. because i think 小瓶s are floating in the sea.
but this reason is too cheap...

----

I want to wrote more and more things but i'm sleepy now.
So i suggest more ideas tomorrow... :zzz:

**Comment by c-bata** [comment]
@denari  Thanks for your logical suggestions. Especially I favorited the san francisco and the reason to choice. 
I'm looking forward to your further suggestions.

**Comment by denari** [comment]
"tomorrow" had come... :bow: 
Now I present 3 gifts for you .

![2016-02-28 14 48 09](https://cloud.githubusercontent.com/assets/5387939/13377726/a7002a16-de2a-11e5-96e3-a9e16f3fc1d2.png)
![2016-02-28 14 48 16](https://cloud.githubusercontent.com/assets/5387939/13377725/a700381c-de2a-11e5-915f-2b9069e414b9.png)
![kobin](https://cloud.githubusercontent.com/assets/5387939/13377728/b8054864-de2a-11e5-8a9d-01762fde1981.png)

Please tell me if you want to use these logos.

**Comment by c-bata** [comment]
@denari May I have your third gift as adobe illustrator style?

**Comment by denari** [comment]
here is 3rd gift
https://www.dropbox.com/s/w7q3oxp1pip3cwo/kobin.ai?dl=0

**Comment by c-bata** [comment]
@denari thx!!!!

**Comment by c-bata** [comment]
Good job.
